# Generated by Django 3.2.15 on 2022-10-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
